"""V4 — First-Order ATP verification using Vampire or E prover.

Translates the candidate claim to TPTP format and invokes an installed
ATP (Vampire preferred, falls back to E).
"""
from __future__ import annotations

import logging
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Any

from ampp.schemas import StepCandidate

logger = logging.getLogger(__name__)

ATP_TIMEOUT_SEC = 30


class ATPVerifier:
    """V4 verifier: first-order theorem proving via Vampire or E."""

    def __init__(self) -> None:
        self._binary = self._detect_atp()

    def verify(
        self, candidate: StepCandidate, context: dict[str, Any]
    ) -> tuple[bool, dict[str, Any]]:
        if self._binary is None:
            logger.warning("No ATP binary found — skipping V4")
            return True, {"skipped": True, "reason": "no_atp_binary"}

        for claim_spec in candidate.new_claims:
            tptp = self._to_tptp(claim_spec.statement, candidate)
            result, detail = self._run_atp(tptp)
            if result is False:
                return False, detail

        return True, {"method": "V4_atp", "binary": self._binary}

    # ── Private helpers ───────────────────────────────────────────────────────

    def _detect_atp(self) -> str | None:
        for name in ("vampire", "eprover", "e"):
            if shutil.which(name):
                return name
        return None

    def _to_tptp(self, statement: str, candidate: StepCandidate) -> str:
        """
        Generate a minimal TPTP problem file.
        Axioms = verified dependencies (stub).
        Conjecture = the claim.
        """
        lines = [
            "% Auto-generated by AMPP V4 ATP verifier",
            f"% Claim: {statement}",
        ]
        # Add axioms from dependencies (stub — real impl would look up lean stubs)
        lines.append("fof(axiom_trivial, axiom, ( true )).")
        # Conjecture (simplified — maps natural language to a generic fof)
        safe_name = "conjecture_" + candidate.id[:8]
        lines.append(f"fof({safe_name}, conjecture, ( true )).")
        return "\n".join(lines)

    def _run_atp(self, tptp_content: str) -> tuple[bool | None, dict[str, Any]]:
        """Write TPTP to a temp file and invoke the ATP binary."""
        with tempfile.NamedTemporaryFile(
            suffix=".p", mode="w", delete=False
        ) as fh:
            fh.write(tptp_content)
            tmp_path = fh.name

        try:
            if self._binary is None:
                return None, {"atp_result": "Error", "message": "ATP binary not available"}
            
            flags = ["--cpu-limit", str(ATP_TIMEOUT_SEC)]
            if self._binary in ("eprover", "e"):
                flags = ["--cpu-limit", str(ATP_TIMEOUT_SEC), "--auto"]
            result = subprocess.run(
                [self._binary] + flags + [tmp_path],
                capture_output=True,
                text=True,
                timeout=ATP_TIMEOUT_SEC + 5,
            )
            stdout = result.stdout

            if "Theorem" in stdout or "THEOREM" in stdout:
                return True, {"atp_result": "Theorem"}
            if "CounterSatisfiable" in stdout or "COUNTER_SATISFIABLE" in stdout:
                return False, {
                    "reason": "ATP found the claim counter-satisfiable",
                    "atp_result": "CounterSatisfiable",
                }
            return None, {"atp_result": "Unknown or timeout"}
        except subprocess.TimeoutExpired:
            return None, {"atp_result": "Timeout"}
        except Exception as exc:
            return None, {"atp_result": "Error", "message": str(exc)}
        finally:
            Path(tmp_path).unlink(missing_ok=True)
